name = "IsoPEPS"
uuid = "ba2a9c53-054a-4f79-8e7e-3842f08de153"
authors = ["yuqingrong"]
version = "1.0.0-DEV"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"

[compat]
Arpack = "0.5.4"
KrylovKit = "0.8.2"
OMEinsum = "0.8.4"
Optimisers = "0.4.1"
SparseArrays = "1.11.0"
TensorOperations = "5.1.2"
Yao = "0.9.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
