name = "IsoPEPS"
uuid = "ba2a9c53-054a-4f79-8e7e-3842f08de153"
version = "1.0.0-DEV"
authors = ["yuqingrong"]

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
FDM = "e25cca7e-83ef-51fa-be6c-dfe2a3123128"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPSKit = "bb1c41ca-d63c-52ed-829e-0820dda26502"
MPSKitModels = "ca635005-6f8c-4cd1-b51d-8491250ef2ab"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
Manopt = "0fc0a36d-df90-57f3-8f93-d78a9fc72bb5"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
OMEinsumContractionOrders = "6f22d1fd-8eed-4bb7-9776-e7d684900715"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
YaoBlocks = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"
YaoPlots = "32cfe2d9-419e-45f2-8191-2267705d8dbc"

[compat]
Arpack = "0.5"
Compose = "0.9"
DifferentiationInterface = "0.6"
FDM = "0.6"
FiniteDiff = "2"
FiniteDifferences = "0.12"
GraphPlot = "0.6"
Graphs = "1"
Integrals = "4.7.0"
KrylovKit = "0.8"
MPSKit = "0.13.8"
MPSKitModels = "0.4.4"
Manifolds = "0.10"
Manopt = "0.5"
OMEinsum = "0.8"
OMEinsumContractionOrders = "0.9"
Optim = "1"
Optimisers = "0.4"
Plots = "1"
Random = "1"
RecursiveArrayTools = "3"
Revise = "3.10.0"
SparseArrays = "1"
Statistics = "1"
TensorKit = "0.15.1"
TensorOperations = "5"
Yao = "0.9"
YaoBlocks = "0.13"
YaoPlots = "0.9"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
