name = "IsoPEPS"
uuid = "ba2a9c53-054a-4f79-8e7e-3842f08de153"
authors = ["yuqingrong"]
version = "1.0.0-DEV"

[deps]
CMAEvolutionStrategy = "8d3b24bd-414e-49e0-94fb-163cc3a3e411"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ITensorInfiniteMPS = "1dc1fb26-a137-4954-ae60-1bd4106e95ad"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
MPSKit = "bb1c41ca-d63c-52ed-829e-0820dda26502"
MPSKitModels = "ca635005-6f8c-4cd1-b51d-8491250ef2ab"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
Manopt = "0fc0a36d-df90-57f3-8f93-d78a9fc72bb5"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
OMEinsumContractionOrders = "6f22d1fd-8eed-4bb7-9776-e7d684900715"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationCMAEvolutionStrategy = "bd407f91-200f-4536-9381-e4ba712f53f8"
PEPSKit = "52969e89-939e-4361-9b68-9bc7cde4bdeb"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
YaoBlocks = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"

[sources]
ITensorInfiniteMPS = {url = "https://github.com/ITensor/ITensorInfiniteMPS.jl"}

[compat]
CairoMakie = "0.15"
ITensors = "0.6, 0.7"
JSON3 = "1"
KrylovKit = "0.8, 0.9, 0.10"
LsqFit = "0.15"
MPSKit = "0.13"
MPSKitModels = "0.4"
Manifolds = "0.10, 0.11"
Manopt = "0.5"
OMEinsum = "0.8, 0.9"
OMEinsumContractionOrders = "0.9, 1"
Optim = "1"
Optimization = "4, 5"
OptimizationCMAEvolutionStrategy = "0.3"
PEPSKit = "0.6, 0.7"
Statistics = "1"
TensorKit = "0.14, 0.15, 0.16"
Yao = "0.9"
YaoBlocks = "0.13, 0.14"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
